"""empty message

Revision ID: 552713eb3119
Revises: 655a28db723f
Create Date: 2021-08-21 12:57:45.007337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552713eb3119'
down_revision = '655a28db723f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_table', sa.Column('rate', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_table', 'rate')
    # ### end Alembic commands ###
