"""empty message

Revision ID: 63227dc57577
Revises: 2a5b9bbe8766
Create Date: 2021-08-24 20:07:43.107316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63227dc57577'
down_revision = '2a5b9bbe8766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BOOK',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CUSTOMER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('CHECK_IN_BOOK',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('rent_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['BOOK.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['CUSTOMER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RENTAL_BOOK',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('rent_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['BOOK.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['CUSTOMER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('email', table_name='customer')
    op.drop_index('username', table_name='customer')
    op.drop_table('customer')
    op.drop_table('rental_book')
    op.drop_table('book')
    op.drop_table('check_in_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in_book',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rent_date', sa.DATE(), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='check_in_book_ibfk_1'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='check_in_book_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('book',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_name', mysql.TEXT(collation='utf8mb4_bin'), nullable=False),
    sa.Column('publisher', mysql.TEXT(collation='utf8mb4_bin'), nullable=False),
    sa.Column('author', mysql.VARCHAR(collation='utf8mb4_bin', length=20), nullable=False),
    sa.Column('publication_date', sa.DATE(), nullable=False),
    sa.Column('pages', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('isbn', mysql.VARCHAR(collation='utf8mb4_bin', length=30), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_bin'), nullable=False),
    sa.Column('link', mysql.TEXT(collation='utf8mb4_bin'), nullable=False),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rental_book',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rent_date', sa.DATE(), nullable=False),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='rental_book_ibfk_1'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='rental_book_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_bin', length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_bin', length=30), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_bin', length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'customer', ['username'], unique=False)
    op.create_index('email', 'customer', ['email'], unique=False)
    op.drop_table('RENTAL_BOOK')
    op.drop_table('CHECK_IN_BOOK')
    op.drop_table('CUSTOMER')
    op.drop_table('BOOK')
    # ### end Alembic commands ###
