"""empty message

Revision ID: 655a28db723f
Revises: e522f99ef2af
Create Date: 2021-08-20 23:28:55.242607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '655a28db723f'
down_revision = 'e522f99ef2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books_table', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_table', sa.Column('rate', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
