"""empty message

Revision ID: b8429471f67a
Revises: 2268d2d1ffc7
Create Date: 2021-08-19 17:11:44.799983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8429471f67a'
down_revision = '2268d2d1ffc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books_table', 'pages',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books_table', 'pages',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
