"""empty message

Revision ID: e522f99ef2af
Revises: b8429471f67a
Create Date: 2021-08-20 13:00:50.860350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e522f99ef2af'
down_revision = 'b8429471f67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books_table', sa.Column('stock', sa.Integer(), nullable=False))
    op.alter_column('books_table', 'pages',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books_table', 'pages',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('books_table', 'stock')
    # ### end Alembic commands ###
